import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const trainingEvents = [
  {
    "eventId": "T001",
    "t": 1,
    "monthOfYear": 1,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 107.9,
    "leisureDemandIndex": 140.1,
    "corporateActivityIndex": 119.1,
    "capacityEconomy": 19755,
    "capacityPremium": 2494,
    "competitorCapacityIndex": 99,
    "avgFareEconomy": 4408.9,
    "avgFarePremium": 10194.7,
    "promoIntensity": 1,
    "weatherDisruptionIndex": 1.3,
    "specialEventFlag": 0,
    "economySeats": 19203,
    "premiumEconomySeats": 2340
  },
  {
    "eventId": "T002",
    "t": 2,
    "monthOfYear": 2,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 106,
    "leisureDemandIndex": 113.4,
    "corporateActivityIndex": 114.2,
    "capacityEconomy": 18615,
    "capacityPremium": 2133,
    "competitorCapacityIndex": 100,
    "avgFareEconomy": 3696.8,
    "avgFarePremium": 10018.2,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.9,
    "specialEventFlag": 1,
    "economySeats": 19066,
    "premiumEconomySeats": 1940
  },
  {
    "eventId": "T003",
    "t": 3,
    "monthOfYear": 3,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 102.2,
    "leisureDemandIndex": 112.2,
    "corporateActivityIndex": 111.7,
    "capacityEconomy": 18058,
    "capacityPremium": 2198,
    "competitorCapacityIndex": 100,
    "avgFareEconomy": 3367.8,
    "avgFarePremium": 10171.2,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 0.3,
    "specialEventFlag": 1,
    "economySeats": 20090,
    "premiumEconomySeats": 1993
  },
  {
    "eventId": "T004",
    "t": 4,
    "monthOfYear": 4,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 99,
    "leisureDemandIndex": 140.2,
    "corporateActivityIndex": 107.8,
    "capacityEconomy": 17882,
    "capacityPremium": 2286,
    "competitorCapacityIndex": 102,
    "avgFareEconomy": 3592.9,
    "avgFarePremium": 9520.3,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1,
    "specialEventFlag": 0,
    "economySeats": 19601,
    "premiumEconomySeats": 1709
  },
  {
    "eventId": "T005",
    "t": 5,
    "monthOfYear": 5,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 95.9,
    "leisureDemandIndex": 146.7,
    "corporateActivityIndex": 105,
    "capacityEconomy": 18110,
    "capacityPremium": 2265,
    "competitorCapacityIndex": 107,
    "avgFareEconomy": 3406.3,
    "avgFarePremium": 9788.9,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 0.8,
    "specialEventFlag": 0,
    "economySeats": 19701,
    "premiumEconomySeats": 1840
  },
  {
    "eventId": "T006",
    "t": 6,
    "monthOfYear": 6,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 93.5,
    "leisureDemandIndex": 141.2,
    "corporateActivityIndex": 111,
    "capacityEconomy": 18337,
    "capacityPremium": 2206,
    "competitorCapacityIndex": 92,
    "avgFareEconomy": 3485.8,
    "avgFarePremium": 10270.5,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 0.9,
    "specialEventFlag": 0,
    "economySeats": 18481,
    "premiumEconomySeats": 1679
  },
  {
    "eventId": "T007",
    "t": 7,
    "monthOfYear": 7,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 91.4,
    "leisureDemandIndex": 104.2,
    "corporateActivityIndex": 104.8,
    "capacityEconomy": 18351,
    "capacityPremium": 2231,
    "competitorCapacityIndex": 101,
    "avgFareEconomy": 3783.4,
    "avgFarePremium": 9587.7,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 3.7,
    "specialEventFlag": 0,
    "economySeats": 16890,
    "premiumEconomySeats": 1780
  },
  {
    "eventId": "T008",
    "t": 8,
    "monthOfYear": 8,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 92.6,
    "leisureDemandIndex": 98.2,
    "corporateActivityIndex": 98.4,
    "capacityEconomy": 17886,
    "capacityPremium": 2138,
    "competitorCapacityIndex": 103,
    "avgFareEconomy": 3679,
    "avgFarePremium": 9588.5,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 6,
    "specialEventFlag": 1,
    "economySeats": 17971,
    "premiumEconomySeats": 1856
  },
  {
    "eventId": "T009",
    "t": 9,
    "monthOfYear": 9,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 95.5,
    "leisureDemandIndex": 94.7,
    "corporateActivityIndex": 98.2,
    "capacityEconomy": 18396,
    "capacityPremium": 2235,
    "competitorCapacityIndex": 104,
    "avgFareEconomy": 3461.8,
    "avgFarePremium": 9891.1,
    "promoIntensity": 1,
    "weatherDisruptionIndex": 7.5,
    "specialEventFlag": 0,
    "economySeats": 17107,
    "premiumEconomySeats": 1862
  },
  {
    "eventId": "T010",
    "t": 10,
    "monthOfYear": 10,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 99.7,
    "leisureDemandIndex": 141.4,
    "corporateActivityIndex": 125.9,
    "capacityEconomy": 19991,
    "capacityPremium": 2389,
    "competitorCapacityIndex": 102,
    "avgFareEconomy": 3947.5,
    "avgFarePremium": 10474.1,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 0.6,
    "specialEventFlag": 0,
    "economySeats": 20242,
    "premiumEconomySeats": 2120
  },
  {
    "eventId": "T011",
    "t": 11,
    "monthOfYear": 11,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 104.8,
    "leisureDemandIndex": 144.5,
    "corporateActivityIndex": 126.8,
    "capacityEconomy": 20947,
    "capacityPremium": 2435,
    "competitorCapacityIndex": 96,
    "avgFareEconomy": 4071.9,
    "avgFarePremium": 10240.4,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 0.9,
    "specialEventFlag": 0,
    "economySeats": 21531,
    "premiumEconomySeats": 2415
  },
  {
    "eventId": "T012",
    "t": 12,
    "monthOfYear": 12,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 108.1,
    "leisureDemandIndex": 155.8,
    "corporateActivityIndex": 105.9,
    "capacityEconomy": 20731,
    "capacityPremium": 2378,
    "competitorCapacityIndex": 105,
    "avgFareEconomy": 3905.3,
    "avgFarePremium": 10663.8,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.2,
    "specialEventFlag": 1,
    "economySeats": 21523,
    "premiumEconomySeats": 2367
  },
  {
    "eventId": "T013",
    "t": 13,
    "monthOfYear": 1,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 110.2,
    "leisureDemandIndex": 146,
    "corporateActivityIndex": 117.4,
    "capacityEconomy": 19679,
    "capacityPremium": 2466,
    "competitorCapacityIndex": 111,
    "avgFareEconomy": 4046,
    "avgFarePremium": 10514.9,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.3,
    "specialEventFlag": 0,
    "economySeats": 20851,
    "premiumEconomySeats": 2319
  },
  {
    "eventId": "T014",
    "t": 14,
    "monthOfYear": 2,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 109.4,
    "leisureDemandIndex": 122.2,
    "corporateActivityIndex": 127.3,
    "capacityEconomy": 18445,
    "capacityPremium": 2365,
    "competitorCapacityIndex": 98,
    "avgFareEconomy": 3652.7,
    "avgFarePremium": 10126.5,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 0.8,
    "specialEventFlag": 0,
    "economySeats": 18824,
    "premiumEconomySeats": 2220
  },
  {
    "eventId": "T015",
    "t": 15,
    "monthOfYear": 3,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 107,
    "leisureDemandIndex": 113,
    "corporateActivityIndex": 115,
    "capacityEconomy": 18015,
    "capacityPremium": 2302,
    "competitorCapacityIndex": 108,
    "avgFareEconomy": 3793.4,
    "avgFarePremium": 10040.5,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 0.8,
    "specialEventFlag": 0,
    "economySeats": 18478,
    "premiumEconomySeats": 2005
  },
  {
    "eventId": "T016",
    "t": 16,
    "monthOfYear": 4,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 103.8,
    "leisureDemandIndex": 134,
    "corporateActivityIndex": 104.6,
    "capacityEconomy": 18404,
    "capacityPremium": 2324,
    "competitorCapacityIndex": 104,
    "avgFareEconomy": 3682.4,
    "avgFarePremium": 10552.3,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 0.4,
    "specialEventFlag": 0,
    "economySeats": 20865,
    "premiumEconomySeats": 2016
  },
  {
    "eventId": "T017",
    "t": 17,
    "monthOfYear": 5,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 98,
    "leisureDemandIndex": 135.3,
    "corporateActivityIndex": 112.9,
    "capacityEconomy": 18806,
    "capacityPremium": 2306,
    "competitorCapacityIndex": 105,
    "avgFareEconomy": 3209.9,
    "avgFarePremium": 9767,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.2,
    "specialEventFlag": 0,
    "economySeats": 20464,
    "premiumEconomySeats": 2020
  },
  {
    "eventId": "T018",
    "t": 18,
    "monthOfYear": 6,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 94.5,
    "leisureDemandIndex": 136.4,
    "corporateActivityIndex": 108.2,
    "capacityEconomy": 19202,
    "capacityPremium": 2308,
    "competitorCapacityIndex": 101,
    "avgFareEconomy": 3569.1,
    "avgFarePremium": 9210,
    "promoIntensity": 1,
    "weatherDisruptionIndex": 0.6,
    "specialEventFlag": 0,
    "economySeats": 20913,
    "premiumEconomySeats": 2056
  },
  {
    "eventId": "T019",
    "t": 19,
    "monthOfYear": 7,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 92.7,
    "leisureDemandIndex": 118.3,
    "corporateActivityIndex": 110.8,
    "capacityEconomy": 18468,
    "capacityPremium": 2256,
    "competitorCapacityIndex": 104,
    "avgFareEconomy": 3565.5,
    "avgFarePremium": 10293.5,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 3.3,
    "specialEventFlag": 1,
    "economySeats": 19088,
    "premiumEconomySeats": 2216
  },
  {
    "eventId": "T020",
    "t": 20,
    "monthOfYear": 8,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 92.8,
    "leisureDemandIndex": 100,
    "corporateActivityIndex": 110.6,
    "capacityEconomy": 18538,
    "capacityPremium": 2345,
    "competitorCapacityIndex": 111,
    "avgFareEconomy": 3613.6,
    "avgFarePremium": 9657.7,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 6.7,
    "specialEventFlag": 1,
    "economySeats": 18127,
    "premiumEconomySeats": 1990
  },
  {
    "eventId": "T021",
    "t": 21,
    "monthOfYear": 9,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 95.3,
    "leisureDemandIndex": 109.7,
    "corporateActivityIndex": 113.6,
    "capacityEconomy": 17981,
    "capacityPremium": 2318,
    "competitorCapacityIndex": 109,
    "avgFareEconomy": 3829.2,
    "avgFarePremium": 9845.1,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 3.3,
    "specialEventFlag": 1,
    "economySeats": 18850,
    "premiumEconomySeats": 1978
  },
  {
    "eventId": "T022",
    "t": 22,
    "monthOfYear": 10,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 101,
    "leisureDemandIndex": 139.6,
    "corporateActivityIndex": 131.5,
    "capacityEconomy": 20315,
    "capacityPremium": 2650,
    "competitorCapacityIndex": 114,
    "avgFareEconomy": 3777.8,
    "avgFarePremium": 10568,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 0.5,
    "specialEventFlag": 0,
    "economySeats": 20929,
    "premiumEconomySeats": 2223
  },
  {
    "eventId": "T023",
    "t": 23,
    "monthOfYear": 11,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 104,
    "leisureDemandIndex": 150.1,
    "corporateActivityIndex": 125.6,
    "capacityEconomy": 19995,
    "capacityPremium": 2614,
    "competitorCapacityIndex": 112,
    "avgFareEconomy": 4023.6,
    "avgFarePremium": 9716.6,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.1,
    "specialEventFlag": 0,
    "economySeats": 20575,
    "premiumEconomySeats": 2403
  },
  {
    "eventId": "T024",
    "t": 24,
    "monthOfYear": 12,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 108.2,
    "leisureDemandIndex": 147.4,
    "corporateActivityIndex": 116.9,
    "capacityEconomy": 20248,
    "capacityPremium": 2525,
    "competitorCapacityIndex": 109,
    "avgFareEconomy": 4201,
    "avgFarePremium": 9860.7,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.1,
    "specialEventFlag": 0,
    "economySeats": 21315,
    "premiumEconomySeats": 2351
  },
  {
    "eventId": "T025",
    "t": 25,
    "monthOfYear": 1,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 107.5,
    "leisureDemandIndex": 144.6,
    "corporateActivityIndex": 116,
    "capacityEconomy": 20149,
    "capacityPremium": 2439,
    "competitorCapacityIndex": 114,
    "avgFareEconomy": 3877.7,
    "avgFarePremium": 9769.2,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.4,
    "specialEventFlag": 0,
    "economySeats": 21707,
    "premiumEconomySeats": 2465
  },
  {
    "eventId": "T026",
    "t": 26,
    "monthOfYear": 2,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 106.2,
    "leisureDemandIndex": 115.7,
    "corporateActivityIndex": 126.5,
    "capacityEconomy": 19002,
    "capacityPremium": 2267,
    "competitorCapacityIndex": 110,
    "avgFareEconomy": 3789.9,
    "avgFarePremium": 9639.3,
    "promoIntensity": 1,
    "weatherDisruptionIndex": 1.3,
    "specialEventFlag": 0,
    "economySeats": 20103,
    "premiumEconomySeats": 2309
  },
  {
    "eventId": "T027",
    "t": 27,
    "monthOfYear": 3,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 103.6,
    "leisureDemandIndex": 112.8,
    "corporateActivityIndex": 123.2,
    "capacityEconomy": 18377,
    "capacityPremium": 2457,
    "competitorCapacityIndex": 111,
    "avgFareEconomy": 3647.2,
    "avgFarePremium": 9958.5,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.3,
    "specialEventFlag": 0,
    "economySeats": 19743,
    "premiumEconomySeats": 2209
  },
  {
    "eventId": "T028",
    "t": 28,
    "monthOfYear": 4,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 100.4,
    "leisureDemandIndex": 143.8,
    "corporateActivityIndex": 109.9,
    "capacityEconomy": 18533,
    "capacityPremium": 2389,
    "competitorCapacityIndex": 107,
    "avgFareEconomy": 3701.4,
    "avgFarePremium": 9981.3,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 0.6,
    "specialEventFlag": 0,
    "economySeats": 21676,
    "premiumEconomySeats": 2143
  },
  {
    "eventId": "T029",
    "t": 29,
    "monthOfYear": 5,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 97.2,
    "leisureDemandIndex": 138.3,
    "corporateActivityIndex": 112.1,
    "capacityEconomy": 20012,
    "capacityPremium": 2412,
    "competitorCapacityIndex": 109,
    "avgFareEconomy": 3405.3,
    "avgFarePremium": 9886.3,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.6,
    "specialEventFlag": 0,
    "economySeats": 21805,
    "premiumEconomySeats": 2093
  },
  {
    "eventId": "T030",
    "t": 30,
    "monthOfYear": 6,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 95.1,
    "leisureDemandIndex": 134.1,
    "corporateActivityIndex": 115.4,
    "capacityEconomy": 18685,
    "capacityPremium": 2240,
    "competitorCapacityIndex": 106,
    "avgFareEconomy": 3673,
    "avgFarePremium": 9403.4,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.1,
    "specialEventFlag": 0,
    "economySeats": 20571,
    "premiumEconomySeats": 2186
  },
  {
    "eventId": "T031",
    "t": 31,
    "monthOfYear": 7,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 92.34,
    "leisureDemandIndex": 118.14,
    "corporateActivityIndex": 110.35,
    "capacityEconomy": 18492,
    "capacityPremium": 2255,
    "competitorCapacityIndex": 104,
    "avgFareEconomy": 3566.31,
    "avgFarePremium": 10296.55,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 3.44,
    "specialEventFlag": 1,
    "economySeats": 19033,
    "premiumEconomySeats": 2206
  },
  {
    "eventId": "T032",
    "t": 32,
    "monthOfYear": 8,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 92.93,
    "leisureDemandIndex": 100.12,
    "corporateActivityIndex": 110.73,
    "capacityEconomy": 18561,
    "capacityPremium": 2346,
    "competitorCapacityIndex": 111,
    "avgFareEconomy": 3613.95,
    "avgFarePremium": 9661.76,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 6.73,
    "specialEventFlag": 1,
    "economySeats": 18078,
    "premiumEconomySeats": 1986
  },
  {
    "eventId": "T033",
    "t": 33,
    "monthOfYear": 9,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 94.99,
    "leisureDemandIndex": 109.88,
    "corporateActivityIndex": 113.51,
    "capacityEconomy": 17989,
    "capacityPremium": 2320,
    "competitorCapacityIndex": 109,
    "avgFareEconomy": 3833.75,
    "avgFarePremium": 9863.56,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 3.3,
    "specialEventFlag": 1,
    "economySeats": 18825,
    "premiumEconomySeats": 1975
  },
  {
    "eventId": "T034",
    "t": 34,
    "monthOfYear": 10,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 99.54,
    "leisureDemandIndex": 140.92,
    "corporateActivityIndex": 125.57,
    "capacityEconomy": 19988,
    "capacityPremium": 2392,
    "competitorCapacityIndex": 102,
    "avgFareEconomy": 3954.49,
    "avgFarePremium": 10477.72,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 0.6,
    "specialEventFlag": 0,
    "economySeats": 20210,
    "premiumEconomySeats": 2130
  },
  {
    "eventId": "T035",
    "t": 35,
    "monthOfYear": 11,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 104.7,
    "leisureDemandIndex": 150.9,
    "corporateActivityIndex": 125.25,
    "capacityEconomy": 19954,
    "capacityPremium": 2615,
    "competitorCapacityIndex": 112,
    "avgFareEconomy": 4036.78,
    "avgFarePremium": 9715,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.14,
    "specialEventFlag": 0,
    "economySeats": 20632,
    "premiumEconomySeats": 2405
  },
  {
    "eventId": "T036",
    "t": 36,
    "monthOfYear": 12,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 108.09,
    "leisureDemandIndex": 147.63,
    "corporateActivityIndex": 116.78,
    "capacityEconomy": 20251,
    "capacityPremium": 2523,
    "competitorCapacityIndex": 109,
    "avgFareEconomy": 4205.04,
    "avgFarePremium": 9845.34,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.18,
    "specialEventFlag": 0,
    "economySeats": 21322,
    "premiumEconomySeats": 2367
  },
  {
    "eventId": "T037",
    "t": 37,
    "monthOfYear": 1,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 107.37,
    "leisureDemandIndex": 143.83,
    "corporateActivityIndex": 115.97,
    "capacityEconomy": 20152,
    "capacityPremium": 2443,
    "competitorCapacityIndex": 115,
    "avgFareEconomy": 3883.63,
    "avgFarePremium": 9772.63,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.41,
    "specialEventFlag": 0,
    "economySeats": 21733,
    "premiumEconomySeats": 2458
  },
  {
    "eventId": "T038",
    "t": 38,
    "monthOfYear": 2,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 106.1,
    "leisureDemandIndex": 115.74,
    "corporateActivityIndex": 125.92,
    "capacityEconomy": 18953,
    "capacityPremium": 2271,
    "competitorCapacityIndex": 110,
    "avgFareEconomy": 3774.06,
    "avgFarePremium": 9631.2,
    "promoIntensity": 1,
    "weatherDisruptionIndex": 1.38,
    "specialEventFlag": 0,
    "economySeats": 20110,
    "premiumEconomySeats": 2310
  },
  {
    "eventId": "T039",
    "t": 39,
    "monthOfYear": 3,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 102.11,
    "leisureDemandIndex": 112.11,
    "corporateActivityIndex": 111.64,
    "capacityEconomy": 18028,
    "capacityPremium": 2199,
    "competitorCapacityIndex": 100,
    "avgFareEconomy": 3374.2,
    "avgFarePremium": 10192.81,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 0.36,
    "specialEventFlag": 1,
    "economySeats": 20078,
    "premiumEconomySeats": 1982
  },
  {
    "eventId": "T040",
    "t": 40,
    "monthOfYear": 4,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 99.39,
    "leisureDemandIndex": 139.29,
    "corporateActivityIndex": 107.48,
    "capacityEconomy": 17911,
    "capacityPremium": 2277,
    "competitorCapacityIndex": 101,
    "avgFareEconomy": 3593.19,
    "avgFarePremium": 9508.17,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 0.87,
    "specialEventFlag": 0,
    "economySeats": 19601,
    "premiumEconomySeats": 1712
  },
  {
    "eventId": "T041",
    "t": 41,
    "monthOfYear": 5,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 97.89,
    "leisureDemandIndex": 134.24,
    "corporateActivityIndex": 112.28,
    "capacityEconomy": 18834,
    "capacityPremium": 2309,
    "competitorCapacityIndex": 105,
    "avgFareEconomy": 3213.05,
    "avgFarePremium": 9770.86,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.18,
    "specialEventFlag": 0,
    "economySeats": 20442,
    "premiumEconomySeats": 2019
  },
  {
    "eventId": "T042",
    "t": 42,
    "monthOfYear": 6,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 95.16,
    "leisureDemandIndex": 134.78,
    "corporateActivityIndex": 115.95,
    "capacityEconomy": 18675,
    "capacityPremium": 2247,
    "competitorCapacityIndex": 106,
    "avgFareEconomy": 3662.17,
    "avgFarePremium": 9385.46,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.1,
    "specialEventFlag": 0,
    "economySeats": 20563,
    "premiumEconomySeats": 2179
  },
  {
    "eventId": "T043",
    "t": 43,
    "monthOfYear": 7,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 91.24,
    "leisureDemandIndex": 104.46,
    "corporateActivityIndex": 105.24,
    "capacityEconomy": 18316,
    "capacityPremium": 2234,
    "competitorCapacityIndex": 101,
    "avgFareEconomy": 3762.4,
    "avgFarePremium": 9592.07,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 3.81,
    "specialEventFlag": 0,
    "economySeats": 16887,
    "premiumEconomySeats": 1776
  },
  {
    "eventId": "T044",
    "t": 44,
    "monthOfYear": 8,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 92.88,
    "leisureDemandIndex": 98.31,
    "corporateActivityIndex": 98.24,
    "capacityEconomy": 17881,
    "capacityPremium": 2135,
    "competitorCapacityIndex": 103,
    "avgFareEconomy": 3684.66,
    "avgFarePremium": 9599.24,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 6.05,
    "specialEventFlag": 1,
    "economySeats": 17984,
    "premiumEconomySeats": 1857
  },
  {
    "eventId": "T045",
    "t": 45,
    "monthOfYear": 9,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 94.97,
    "leisureDemandIndex": 109.42,
    "corporateActivityIndex": 113.89,
    "capacityEconomy": 18002,
    "capacityPremium": 2323,
    "competitorCapacityIndex": 109,
    "avgFareEconomy": 3836.86,
    "avgFarePremium": 9831.67,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 3.32,
    "specialEventFlag": 1,
    "economySeats": 18835,
    "premiumEconomySeats": 1979
  },
  {
    "eventId": "T046",
    "t": 46,
    "monthOfYear": 10,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 101.38,
    "leisureDemandIndex": 139.67,
    "corporateActivityIndex": 131.46,
    "capacityEconomy": 20289,
    "capacityPremium": 2654,
    "competitorCapacityIndex": 113,
    "avgFareEconomy": 3763.2,
    "avgFarePremium": 10572.95,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 0.46,
    "specialEventFlag": 0,
    "economySeats": 20920,
    "premiumEconomySeats": 2213
  },
  {
    "eventId": "T047",
    "t": 47,
    "monthOfYear": 11,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 104.05,
    "leisureDemandIndex": 150.5,
    "corporateActivityIndex": 126.19,
    "capacityEconomy": 19997,
    "capacityPremium": 2620,
    "competitorCapacityIndex": 112,
    "avgFareEconomy": 4026.44,
    "avgFarePremium": 9710.05,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.02,
    "specialEventFlag": 0,
    "economySeats": 20649,
    "premiumEconomySeats": 2415
  },
  {
    "eventId": "T048",
    "t": 48,
    "monthOfYear": 12,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 108.04,
    "leisureDemandIndex": 156.32,
    "corporateActivityIndex": 105.73,
    "capacityEconomy": 20704,
    "capacityPremium": 2380,
    "competitorCapacityIndex": 105,
    "avgFareEconomy": 3900.21,
    "avgFarePremium": 10676.06,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.23,
    "specialEventFlag": 1,
    "economySeats": 21489,
    "premiumEconomySeats": 2362
  },
  {
    "eventId": "T049",
    "t": 49,
    "monthOfYear": 1,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 110.26,
    "leisureDemandIndex": 147.09,
    "corporateActivityIndex": 116.81,
    "capacityEconomy": 19675,
    "capacityPremium": 2467,
    "competitorCapacityIndex": 111,
    "avgFareEconomy": 4052.76,
    "avgFarePremium": 10489.1,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.27,
    "specialEventFlag": 0,
    "economySeats": 20914,
    "premiumEconomySeats": 2326
  },
  {
    "eventId": "T050",
    "t": 50,
    "monthOfYear": 2,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 108.85,
    "leisureDemandIndex": 121.56,
    "corporateActivityIndex": 127.4,
    "capacityEconomy": 18443,
    "capacityPremium": 2363,
    "competitorCapacityIndex": 98,
    "avgFareEconomy": 3649.78,
    "avgFarePremium": 10124.66,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 0.8,
    "specialEventFlag": 0,
    "economySeats": 18783,
    "premiumEconomySeats": 2222
  },
  {
    "eventId": "T051",
    "t": 51,
    "monthOfYear": 3,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 103.74,
    "leisureDemandIndex": 111.94,
    "corporateActivityIndex": 123.08,
    "capacityEconomy": 18360,
    "capacityPremium": 2459,
    "competitorCapacityIndex": 112,
    "avgFareEconomy": 3657.75,
    "avgFarePremium": 9971.29,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.27,
    "specialEventFlag": 0,
    "economySeats": 19753,
    "premiumEconomySeats": 2206
  },
  {
    "eventId": "T052",
    "t": 52,
    "monthOfYear": 4,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 103.64,
    "leisureDemandIndex": 133.46,
    "corporateActivityIndex": 104.82,
    "capacityEconomy": 18355,
    "capacityPremium": 2326,
    "competitorCapacityIndex": 103,
    "avgFareEconomy": 3691.86,
    "avgFarePremium": 10559.34,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 0.35,
    "specialEventFlag": 0,
    "economySeats": 20908,
    "premiumEconomySeats": 2016
  },
  {
    "eventId": "T053",
    "t": 53,
    "monthOfYear": 5,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 97.61,
    "leisureDemandIndex": 136.56,
    "corporateActivityIndex": 112.25,
    "capacityEconomy": 18822,
    "capacityPremium": 2305,
    "competitorCapacityIndex": 105,
    "avgFareEconomy": 3205.33,
    "avgFarePremium": 9756.85,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.07,
    "specialEventFlag": 0,
    "economySeats": 20437,
    "premiumEconomySeats": 2020
  },
  {
    "eventId": "T054",
    "t": 54,
    "monthOfYear": 6,
    "isSummerVacation": 1,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 94.17,
    "leisureDemandIndex": 136.32,
    "corporateActivityIndex": 107.98,
    "capacityEconomy": 19184,
    "capacityPremium": 2307,
    "competitorCapacityIndex": 101,
    "avgFareEconomy": 3566.8,
    "avgFarePremium": 9218.48,
    "promoIntensity": 1,
    "weatherDisruptionIndex": 0.54,
    "specialEventFlag": 0,
    "economySeats": 20922,
    "premiumEconomySeats": 2053
  },
  {
    "eventId": "T055",
    "t": 55,
    "monthOfYear": 7,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 91.1,
    "leisureDemandIndex": 104.9,
    "corporateActivityIndex": 104.44,
    "capacityEconomy": 18370,
    "capacityPremium": 2237,
    "competitorCapacityIndex": 101,
    "avgFareEconomy": 3777.78,
    "avgFarePremium": 9600.79,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 3.63,
    "specialEventFlag": 0,
    "economySeats": 16900,
    "premiumEconomySeats": 1789
  },
  {
    "eventId": "T056",
    "t": 56,
    "monthOfYear": 8,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 92.79,
    "leisureDemandIndex": 99.13,
    "corporateActivityIndex": 98.29,
    "capacityEconomy": 17891,
    "capacityPremium": 2138,
    "competitorCapacityIndex": 103,
    "avgFareEconomy": 3681.75,
    "avgFarePremium": 9587.03,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 6.04,
    "specialEventFlag": 1,
    "economySeats": 17963,
    "premiumEconomySeats": 1857
  },
  {
    "eventId": "T057",
    "t": 57,
    "monthOfYear": 9,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 95.41,
    "leisureDemandIndex": 111.52,
    "corporateActivityIndex": 113.63,
    "capacityEconomy": 17970,
    "capacityPremium": 2312,
    "competitorCapacityIndex": 108,
    "avgFareEconomy": 3816.03,
    "avgFarePremium": 9826.06,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 3.22,
    "specialEventFlag": 1,
    "economySeats": 18863,
    "premiumEconomySeats": 1985
  },
  {
    "eventId": "T058",
    "t": 58,
    "monthOfYear": 10,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 99.63,
    "leisureDemandIndex": 140.98,
    "corporateActivityIndex": 126.22,
    "capacityEconomy": 19987,
    "capacityPremium": 2387,
    "competitorCapacityIndex": 101,
    "avgFareEconomy": 3955.19,
    "avgFarePremium": 10491.14,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 0.67,
    "specialEventFlag": 0,
    "economySeats": 20193,
    "premiumEconomySeats": 2114
  },
  {
    "eventId": "T059",
    "t": 59,
    "monthOfYear": 11,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 104.1,
    "leisureDemandIndex": 150.67,
    "corporateActivityIndex": 125.64,
    "capacityEconomy": 19981,
    "capacityPremium": 2620,
    "competitorCapacityIndex": 111,
    "avgFareEconomy": 4021.01,
    "avgFarePremium": 9731.72,
    "promoIntensity": 0,
    "weatherDisruptionIndex": 1.07,
    "specialEventFlag": 0,
    "economySeats": 20620,
    "premiumEconomySeats": 2396
  },
  {
    "eventId": "T060",
    "t": 60,
    "monthOfYear": 12,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 108.37,
    "leisureDemandIndex": 156.15,
    "corporateActivityIndex": 105.89,
    "capacityEconomy": 20732,
    "capacityPremium": 2376,
    "competitorCapacityIndex": 105,
    "avgFareEconomy": 3899.78,
    "avgFarePremium": 10672.57,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1.11,
    "specialEventFlag": 1,
    "economySeats": 21491,
    "premiumEconomySeats": 2371
  }
];

const gameRounds = [
  {
    "roundNumber": 1,
    "title": "Round 1 (T061): Monsoon Disruption",
    "theme": "Heavy monsoon flooding disrupts operations in the Western region; leisure travel softens and some flights face weather delays.",
    "monthOfYear": 7,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 96,
    "leisureDemandIndex": 101,
    "corporateActivityIndex": 112,
    "capacityEconomy": 19000,
    "capacityPremium": 2200,
    "competitorCapacityIndex": 106,
    "avgFareEconomy": 3550,
    "avgFarePremium": 9300,
    "promoIntensity": 1,
    "weatherDisruptionIndex": 8,
    "specialEventFlag": 0,
    "instructions": "Heavy monsoon flooding disrupts operations in the Western region; leisure travel softens and some flights face weather delays.",
    "actualGa": 16450,
    "actualVip": 1720,
    "status": "ready",
    "timerSeconds": 600
  },
  {
    "roundNumber": 2,
    "title": "Round 2 (T062): Fuel Duty Hike + Independence Day",
    "theme": "Fuel duty hike raises aviation fuel costs; the Independence Day long weekend provides a short leisure-travel bump.",
    "monthOfYear": 8,
    "isSummerVacation": 0,
    "isMonsoon": 1,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 108,
    "leisureDemandIndex": 113,
    "corporateActivityIndex": 114,
    "capacityEconomy": 19800,
    "capacityPremium": 2250,
    "competitorCapacityIndex": 108,
    "avgFareEconomy": 3750,
    "avgFarePremium": 9600,
    "promoIntensity": 1,
    "weatherDisruptionIndex": 4,
    "specialEventFlag": 1,
    "instructions": "Fuel duty hike raises aviation fuel costs; the Independence Day long weekend provides a short leisure-travel bump.",
    "actualGa": 18650,
    "actualVip": 1920,
    "status": "ready",
    "timerSeconds": 600
  },
  {
    "roundNumber": 3,
    "title": "Round 3 (T063): GST Rate Cut",
    "theme": "GST on air tickets is cut and part of the saving is passed to passengers through lower Economy fares; monsoon effects fade and pre-festive bookings pick up.",
    "monthOfYear": 9,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 99,
    "leisureDemandIndex": 121,
    "corporateActivityIndex": 116,
    "capacityEconomy": 20200,
    "capacityPremium": 2300,
    "competitorCapacityIndex": 104,
    "avgFareEconomy": 3400,
    "avgFarePremium": 9200,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 2,
    "specialEventFlag": 0,
    "instructions": "GST on air tickets is cut and part of the saving is passed to passengers through lower Economy fares; monsoon effects fade and pre-festive bookings pick up.",
    "actualGa": 19850,
    "actualVip": 2050,
    "status": "ready",
    "timerSeconds": 600
  },
  {
    "roundNumber": 4,
    "title": "Round 4 (T064): Diwali Festive Peak",
    "theme": "Diwali creates the year's strongest leisure/home-travel peak; capacity is stretched, fares firm, and the airline makes a modest promotional push.",
    "monthOfYear": 10,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 0,
    "fuelPriceIndex": 101,
    "leisureDemandIndex": 145,
    "corporateActivityIndex": 118,
    "capacityEconomy": 21400,
    "capacityPremium": 2400,
    "competitorCapacityIndex": 103,
    "avgFareEconomy": 4300,
    "avgFarePremium": 10500,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1,
    "specialEventFlag": 1,
    "instructions": "Diwali creates the year's strongest leisure/home-travel peak; capacity is stretched, fares firm, and the airline makes a modest promotional push.",
    "actualGa": 21200,
    "actualVip": 2280,
    "status": "ready",
    "timerSeconds": 600
  },
  {
    "roundNumber": 5,
    "title": "Round 5 (T065): Wedding Season + Corporate Year-End",
    "theme": "Peak wedding season combines with corporate year-end travel; Premium Economy demand is particularly strong.",
    "monthOfYear": 11,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 0,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 103,
    "leisureDemandIndex": 139,
    "corporateActivityIndex": 130,
    "capacityEconomy": 22000,
    "capacityPremium": 2500,
    "competitorCapacityIndex": 102,
    "avgFareEconomy": 4100,
    "avgFarePremium": 10800,
    "promoIntensity": 2,
    "weatherDisruptionIndex": 1,
    "specialEventFlag": 0,
    "instructions": "Peak wedding season combines with corporate year-end travel; Premium Economy demand is particularly strong.",
    "actualGa": 21650,
    "actualVip": 2450,
    "status": "ready",
    "timerSeconds": 600
  },
  {
    "roundNumber": 6,
    "title": "Round 6 (T066): New Year Holidays",
    "theme": "Christmas/New Year leisure travel remains strong, but corporate travel becomes cautious ahead of the Union Budget, creating stronger Economy and softer Premium demand.",
    "monthOfYear": 12,
    "isSummerVacation": 0,
    "isMonsoon": 0,
    "isFestiveHoliday": 1,
    "isWeddingSeason": 1,
    "fuelPriceIndex": 102,
    "leisureDemandIndex": 132,
    "corporateActivityIndex": 104,
    "capacityEconomy": 21800,
    "capacityPremium": 2450,
    "competitorCapacityIndex": 101,
    "avgFareEconomy": 3950,
    "avgFarePremium": 10100,
    "promoIntensity": 1,
    "weatherDisruptionIndex": 1,
    "specialEventFlag": 1,
    "instructions": "Christmas/New Year leisure travel remains strong, but corporate travel becomes cautious ahead of the Union Budget, creating stronger Economy and softer Premium demand.",
    "actualGa": 21100,
    "actualVip": 2320,
    "status": "ready",
    "timerSeconds": 600
  }
];

async function main() {
  console.log('Starting seeding...');

  // Create Admin User
  const passwordHash = await bcrypt.hash('Admin@123', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@aeronexus.com' },
    update: {},
    create: {
      name: 'Admin',
      email: 'admin@aeronexus.com',
      passwordHash,
      role: 'ADMIN',
    },
  });
  console.log('Admin user created:', admin.email);

  // Clear existing training events and game rounds (optional but good for clean seed)
  await prisma.trainingEvent.deleteMany({});
  await prisma.gameRound.deleteMany({});
  
  // Create Training Events
  console.log('Creating training events...');
  for (const event of trainingEvents) {
    await prisma.trainingEvent.create({ data: event });
  }
  console.log(`Created ${trainingEvents.length} training events.`);

  // Create Game Rounds
  console.log('Creating game rounds...');
  for (const round of gameRounds) {
    await prisma.gameRound.create({ data: round });
  }
  console.log(`Created ${gameRounds.length} game rounds.`);

  // Create Default Scoring Config
  const config = await prisma.scoringConfig.findFirst();
  if (!config) {
    await prisma.scoringConfig.create({
      data: {
        gaWeight: 0.6,
        vipWeight: 0.4,
        maxRoundScore: 1000,
        underForecastPenalty: 1.0,
        overForecastPenalty: 1.0,
        active: true,
      },
    });
    console.log('Created default scoring config.');
  }

  // Create Default Game Control
  const control = await prisma.gameControl.findFirst();
  if (!control) {
    await prisma.gameControl.create({
      data: {
        gameStatus: 'active',
        timerEnabled: true,
        leaderboardEnabled: false,
        activeRound: 1,
      },
    });
    console.log('Created default game control.');
  }

  console.log('Seeding finished successfully.');
}

main()
  .catch((e) => {
    console.error('Error seeding data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
